Sistema de Ventas/Sistema de Ventas/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sistema_de_Ventas.Models;

namespace Tarea_LoginyTablaUsuario.Controllers
{
   
    public class LoginController : Controller
    {
        SistemaVentasEntities db = new SistemaVentasEntities();
        // GET: Login
        public ActionResult Index()
        {
            Session["Usuario"] = null;
            return View();   
        }
      
        [HttpPost]
        public ActionResult Index(string txtusuario, string txtpassword)
        {
            Session["Usuario"] = null;
            var login = db.UDP_Login(txtusuario, txtpassword).ToList();
        if (login.Count() > 0)
            {
                foreach (var item in login)
                {
                    Session["EmpleadoID"] = item.empleadoId.ToString();
                }
                Session["Usuario"] = txtusuario;
                return RedirectToAction("Index", "Home","Home");
            }
            else
            {
                ModelState.AddModelError("Validador", "El Usuario/Contraseña son incorrectos.");
            }
            return View();
        }

        public ActionResult RecuperarContrasena()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CambioContrasena(string txtusuario, string txtpassword)
        {
            var usuario = db.UDP_SelectUsuario(txtusuario).ToList();
            string cadena = "";
            if (usuario.Count() > 0)
            {
                db.UDP_CambiarContrasenia(txtusuario, txtpassword);
                cadena = "Index";
            }
            else
            {
                ModelState.AddModelError("Validador", "El Usuario es Incorrecto.");
                cadena = "RecuperarContrasena";
            }
                return View(cadena);
        }

    }


   
}

Sistema de Ventas/Sistema de Ventas/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Login 08</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/Content/dist/css/stylelogin.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-5">
                    <div class="login-wrap p-4 p-md-5" style="height: 550px">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Iniciar Sesion</h3>
                        <form action="@Url.Action("Index","Login")" method="post" class="login-form">
                            <div class="form-group">
                                <input type="text" class="form-control rounded-left" placeholder="Usuario" name="txtusuario" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" placeholder="contraseña" name="txtpassword" required>
                            </div>
                            <label style="color:red">@Html.ValidationMessage("Validador")</label>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Recuerdame
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="/login/RecuperarContrasena">¿Olvidaste la contraseña?</a>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary rounded submit p-3 px-5">Iniciar Sesion</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Content/dist/js/jquerylogin.min.js"></script>
    <script src="~/Content/dist/js/popper.min.js"></script>
    <script src="~/Content/dist/js/bootstraplogin.min.js"></script>
    <script src="~/Content/dist/js/mainlogin.js"></script>

</body>
</html>

<script>
    $(document).ready(function () {
        $("#txtusuario").val();
        $("#txtpassword").val();
    })
</script>

Sistema de Ventas/Sistema de Ventas/Views/Login/Login.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Login 08</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/Content/dist/css/stylelogin.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Iniciar Sesion</h3>
                        <form action="@Url.Action("Index","Login")" method="post" class="login-form">
                            <div class="form-group">
                                <input type="text" class="form-control rounded-left" placeholder="Usuario" name="txtusuario" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" placeholder="contraseña" name="txtpassword" required>
                            </div>
                            <label style="color:red">@Html.ValidationMessage("Validador")</label>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Recuerdame
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>

                                <div class="w-50 text-md-right">
                               
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary rounded submit p-3 px-5">Iniciar Sesion</button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Content/dist/js/jquerylogin.min.js"></script>
    <script src="~/Content/dist/js/popper.min.js"></script>
    <script src="~/Content/dist/js/bootstraplogin.min.js"></script>
    <script src="~/Content/dist/js/mainlogin.js"></script>

</body>
</html>

Sistema de Ventas/Sistema de Ventas/Views/Login/RecuperarContrasena.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RecuperarContrasena</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/Content/dist/css/stylelogin.css">
</head>
<body>
    <section class="ftco-section">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-5">
                    <div class="login-wrap p-4 p-md-5" style="height: 500px">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Iniciar Sesion</h3>
                        <form action="@Url.Action("CambioContrasena","Login")" method="post" class="login-form">
                            <div class="form-group">
                                <input type="text" class="form-control rounded-left" placeholder="Usuario" name="txtusuario" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" placeholder="Nueva Contraseña" name="txtpassword" required>
                            </div>
                            <label style="color:red">@Html.ValidationMessage("Validador")</label>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary rounded submit p-3 px-5">Cambiar Contraseña</button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



</body>
</html>
<script src="~/Content/dist/js/jquerylogin.min.js"></script>
<script src="~/Content/dist/js/popper.min.js"></script>
<script src="~/Content/dist/js/bootstraplogin.min.js"></script>
<script src="~/Content/dist/js/mainlogin.js"></script>